### ISSUE TITLE
Evaluation protocol

### ISSUE THREAD

**Issue by Fodark** [neuralchen/SimSwap#12]
First of all, great work!

I wanted to ask you how you evaluated against "Fine-grained head pose estimation without keypoints" for face pose correctness, because the official implementation of the Hopenet works on Python 2.7 with torch 0.4, incompatible with your environment and most modern systems. I was wondering if you used a different or more modern implementation of it.

Thank you!

**Comment by NNNNAI** [comment]
Thank you for your attention to our work! As shown in our paper, we did not do any head pose estimation. Because this is not our key research issue. As for the environment of hopenet you mentioned is a bit old, you can try to forward all the pictures that need to be tested, and then save them in a folder, and then use hopenet to test  the "face pose correctness" for every pictures in this folder. In this way, problems caused by the environment can be avoided. We have released the relevant scripts for face swapping in any picture, you can try my idea to see if it can be solved. If there is any problem, please let me know. Many thanks :).
