### ISSUE TITLE
How to use GPU ?

### ISSUE THREAD

**Issue by DrBlou** [neuralchen/SimSwap#192]
Hello, 

First, thanks a lot for your work its amazing :)

Maybe it was already answered but I can't find the solution, so I'm asking for help 

Simswap is on my SSD
Y have installed onnxruntime-GPU

I can't get higher than 4 it / s, and when I look at component usage, my CPU is almost 80% used while my graphics card is 5% used .. So I deduce that there is something wrong.

Can you help me please ?

thank you very much in advance

![Capture](https://user-images.githubusercontent.com/92190077/148964947-47b9ff57-700f-4398-a4f0-34023157e3ab.PNG)

**Comment by Fibonacci134** [comment]
Hey, what resolution was the input video? 
Also, you can change the set size in the test videoswapsingle.py to make it a bit faster. In order to help, you should list your cpu, gpu, your cuda version, toolkit version, and onnxruntime. You need the proper version of torch as well and tensorflow.

**Comment by DrBlou** [comment]
Hello,

Thank you for your quick reply

No matter the resolution of the video, I always have 4 it / s maximum

Here is the required information :

CPU: Intel Core I9-9900K 3.60Ghz

GPU: Nvidia GTX 980 4GO

Cuda compilation tools, release 11.4, V11.4.48
Build cuda_11.4.r11.4 / compiler.30033411_0

onnxruntime-gpu-1.10.0
 torch-1.10.1


thank you very much

**Comment by beakwood** [comment]
@DrBlou Are you by chance running python 3.10? Because, I just reinstalled and remember this issue here, and I too received the same error as you using 3.10. So I reinstalled using like the requirements stated in the installation and used 3.6 environment and was able to install all dependencies including onyxonetime-gpu==1.9 with no problems. But I was getting "stuck at end" when running so I used [#issuecomment-866039674_ ](https://github.com/neuralchen/SimSwap/issues/15#issuecomment-866039674) to fix my issue. As you can see, the moment I state the process, my GPU is hit. 
![graphgpu](https://user-images.githubusercontent.com/43938224/150267834-7bdfd86b-8570-4be2-ac92-d0ae8a780456.png)

**Comment by DrBlou** [comment]
Hello,

Thanks for coming back to answer my issue :)

I managed to install onnxruntime-gpu 1.9.0

But my GPU is still not used 

I really dont understand :-(

![image](https://user-images.githubusercontent.com/92190077/150399440-016a0542-0f27-4640-b0c1-2300b50d3863.png)

![image](https://user-images.githubusercontent.com/92190077/150399565-71b803f1-ade9-4681-b49e-64fa114c4858.png)

![image](https://user-images.githubusercontent.com/92190077/150399631-f273abc0-0eb1-487f-8606-b7949dae0538.png)

**Comment by Fibonacci134** [comment]
Hmm that is interesting, so I have run the script on both windows and Linux, and had a similar experience in windows as you did with the usage not showing. Do you have the Nvidia app where you can monitor nthe performance/temp etc? Because even though windows showed no usage, the Nvidia software did. I believe the issue is caused by the pre installed Nvidia drivers that windows comes with. One solution is to completely uninstall the driver in device manager and then install the proprietary drivers for your card, directly from Nvidia. This script running on my gtx1650 uses about 2.7 Gb vram. Also check if you have your card set to performance mode or not. When I run this on windows, I make sure to set my CPU to perform and turn off battery saver and make sure to plug in my laptop. Did you see a noticable increase in speed with the data set at 256? I have it pretty well optimized on linux, for a 1280x720 video, I get about 7/its . So the script is definitely using more of your gpu than shown by task manager, now it's just tinkering and optimization. I wish people would post their average inference time so that we would have an idea of where we all stand lol

**Comment by DrBlou** [comment]
Hello, 

I already removed the preinstalled drivers and installed the last ones. I am sure that my GPU is not used at all, it's not a wrong information from the task manager. I turned off battery saving and my power plant is on "high performance" on windows.

i didn't noticed a speed inscrease with 256.

Nevermind, I hope the tool will be updated in the future so I can use my GPU.

Have a nice day

**Comment by Fibonacci134** [comment]
Hmm, good luck. Also keep in mind that inside the task manager, you can also change the graph to show you how much CUDA is using your gpu, (compute mode) even though at the surface it shows 4% it can show you CUDA cores usage. Also, add this to your command --gpu_ids  -1 . This will use your CPU only and will show you if there are any differences in time. Have a good day bro.

**Comment by DrBlou** [comment]
Ok thank you, you too :)
