### ISSUE TITLE
Training time for the provided pretrained model

### ISSUE THREAD

**Issue by shivangi-aneja** [neuralchen/SimSwap#203]
I was wondering if you could provide me with some statistics about how much time it took you to train the publicly available checkpoint. More specifically, if you could provide GPU hours and hardware architecture used for training the SimSwap model. I already wrote an email regarding the same, feel free to revert there.

**Comment by alcanunsal** [comment]
any updates on this? I have also been wondering the same

**Comment by Fibonacci134** [comment]
I believe they have abandoned this project. It's a shame, because it has much potential. Maybe some people will gather resources and carry on from here but I don't expect these guys to be active on this project at the moment. Understandable that they have other projects going on, but a bit of updates would be nice.

**Comment by neuralchen** [comment]
May world peace！
We are working for ECCV2022!
What can be revealed here is that we are developing a tiny face-swapping framework of 512x512.

**Comment by Fibonacci134** [comment]
Great to hear, and yes the world can definitely use peace right now. Best of luck with your ongoing projects. Hope to hear from you guys, and can't wait for beta testing ☺️.

**Comment by neuralchen** [comment]
Training scripts are now available!

**Comment by neuralchen** [comment]
Colab version are available now!
