### ISSUE TITLE
Unnormal face skin colour and swap results is very bad

### ISSUE THREAD

**Issue by netrunner-exe** [neuralchen/SimSwap#242]
After 25000 epoch with 224 dataset  i get: unnormal skin colour and swap results is bad. Might need more epoch to train? Or this is what autors means when saying: "Friendly reminder, due to the difference in training settings, the user-trained model will have subtle differences in visual effects from the pre-trained model we provide"? Perhaps this is a bug that the developers, as always, forgot to fix in the code? I don't know. If at least someone gets normal results that are at least a little similar to the previously posted model of the authors - post a screenshot. A little disappointed, but still hope that the time for training was not wasted.
![frame_0000000](https://user-images.githubusercontent.com/81887288/164998248-a0da155e-505b-4640-9c68-d9fe79505d2c.jpg)

**Comment by YaoQ** [comment]
I got the same issue that the skin color is abnormal with the trained model and `test_one_image.py`.
But you see the generated image  in training process as `samples` is fine.

Seemly the inference code and train code for that part are different, and I also try to fix that.

**Comment by Fibonacci134** [comment]
I would suggest at least 80k iterations to see good results. I haven't used this training script, how many iterations is the 224 pretrained model?

**Comment by neuralchen** [comment]
When batch size is 16, at least 400K iterations are trained. If the device cannot support a relatively large batch size, the number of training iterations far exceeds 400K. 
It is normal for the effect to be poor when batch size is relatively small.
Usually we use V100 for training.

**Comment by osushilover** [comment]
I have a model that has been iterated a million times.
However, using that model, as in the previous problem, I do not see the expected results, as the target face is only converted to white.
This is really annoying because I don't see the white face on the preview, but the error occurs on output.

This model was created after more than a week of training with Tesla V100 in the high memory environment of Colab Pro+
![step_1000000](https://user-images.githubusercontent.com/77590366/170516418-ebc2a0b9-d590-453e-8bc3-9e591e3fb389.jpg)
.

**Comment by nonlin** [comment]
500k iterations 23 batch size and my skin is white.

**Comment by Darth-Zzz** [comment]
Hi, 
I met the same problem. Did you solve it?

**Comment by ChoYongchae** [comment]
> Hi, I met the same problem. Did you solve it?

I hope the answer below helps you.
https://github.com/neuralchen/SimSwap/issues/388#issuecomment-2177451969
