### ISSUE TITLE
Pretrained network G has fewer layers; The following are not initialized: ['down0', 'first_layer', 'last_layer', 'up0']

### ISSUE THREAD

**Issue by doctorcui** [neuralchen/SimSwap#247]

**Comment by JieLiu95** [comment]
Has the problem been solved? How is it solved？ @doctorcui

**Comment by HiddenMarkovModel** [comment]
I encounter the same error, any helps?

**Comment by cjxxu** [comment]
I encounter the same error too

**Comment by geekbleek** [comment]
Same issue - can we re-open this?

**Comment by cj0596** [comment]
Same issue too!

**Comment by arnold408** [comment]
go the same issue

**Comment by KleinXin** [comment]
how to solve?

**Comment by dannytheairish** [comment]
If anyone still have this error, its because the crop_size is by default 512. Change it to 224 if you trying it on the images in folder crop_224.

The easiest way would be if you replace the line in project folder **SimSwap\options\test_options.py** 
`self.parser.add_argument('--crop_size', type=int, default=512, help='Crop of size of input image')`
by
`self.parser.add_argument('--crop_size', type=int, default=224, help='Crop of size of input image')`

Then you can run it via terminal with (just as example):
`py test_one_image.py --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path crop_224/cage.jpg --pic_b_path crop_224/james.jpg --output_path output/`

The final image will be then in the folder output.

Hope it helps you.
