### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by youqugit** [neuralchen/SimSwap#29]
根据Usage所提供的命令运行出现如下错误。
运行的命令：
Face swapping for video
Swap only one face within the video(the one with highest confidence by face detection).
python test_video_swapsingle.py --isTrain false  --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path ./demo_file/Iron_man.jpg --video_path ./demo_file/mutil_people_1080p.mp4 --output_path ./output/mutil_test_swapsingle.mp4 --temp_path ./temp_results
出现的错误：
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 44, in <module>
    app = Face_detect_crop(name='antelope', root='./insightface_func/models')
  File "E:\BaiduNetdiskDownload\SimSwap-main\insightface_func\face_detect_crop_single.py", line 39, in __init__
    assert 'detection' in self.models
AssertionError

**Comment by NNNNAI** [comment]
Make sure you have followed the gudience from [preperation](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md).This bug seems to be that you did not download the pre-trained model of insightface. You should download the relative files and unzip them to ./insightface_func/models from [this link](https://onedrive.live.com/?authkey=%21ADJ0aAOSsc90neY&cid=4A83B6B633B029CC&id=4A83B6B633B029CC%215837&parId=4A83B6B633B029CC%215834&action=locate). Many thanks~.

**Comment by youqugit** [comment]
忘记创建models文件夹了，直接把解压的文件放在./insightface_func这里了。完美解决，谢谢。

**Comment by neuralchen** [comment]
Problem solved!

**Comment by zkchen95** [comment]
> 忘记创建models文件夹了，直接把解压的文件放在./insightface_func这里了。完美解决，谢谢。

你好，压缩文件可以发给我一份吗（1030266968@qq.com）？国内网下不了OneDrive的文件
