### ISSUE TITLE
Retargetting / Puppeteering face from source to target

### ISSUE THREAD

**Issue by johndpope** [neuralchen/SimSwap#45]
Currently this code uses a single image to transfer face look a like

I want to go frame by frame of input video and drive the target face with source motions while maintaining style / colours.

maybe not so simple

**Comment by ftaker887** [comment]
This sounds like more of a use case for[ First Order Motion Model](https://github.com/AliaksandrSiarohin/first-order-model). This repo works by extracting the facial details of the source then placing them on the destination, so remember that if you're looking to extend its functionality. 

Off the top of my head, I don't think it would be very difficult to implement, and you could probably do some funny effects such as freezing the facial expressions. In theory, you could reverse the **facial expression transfer** so that the target face goes onto the source face, but the target face stays on the target video. In other words, the target face *references* the source face, taking its expression. 

A single image for face expression transfer wouldn't be an issue, but what does become an issue are video frames. You would either have to interpolate the frames of the source face to match the target's video length, or loop the source video until the target video reaches the end. 

Hope that helps and gives you an idea or two!

**Comment by woctezuma** [comment]
First, great advice from ftaker!

Second, I think what John mentions is to:
- take as input a video V and an image I,
- generate a video where each frame is similar to I, and where a face comes the corresponding frame of V.

Which is different from the current code, which generates a video similar to V, and where the face is unique and comes from I.

A priori, this should be doable with a bit of looping around.

**Comment by johndpope** [comment]
this is a video of my face thrown into another / superimposed and yes this is face swapping - but it's actually NOT  what I want / or attempting to articulate. https://user-images.githubusercontent.com/289994/124865684-73a7dc00-dffe-11eb-8855-2cd9c74bc733.mov

I want to keep the original persons picture / but use the injection layer to inject motion from my video to drive the lady's facial expressions. It would open up opportunities to redeliver /redirect dialogue from an actor into saying something different. 
"Do that line again - but say the words and move your mouth like this video here....."
